import 'dart:math' as math;
import 'package:flutter/material.dart';
import '../core/darkest_world_navigation_state.dart';
import '../screens/galaxy_navigation_session.dart';

class DarkestWorldLiveDetailChamber extends StatefulWidget { const DarkestWorldLiveDetailChamber({super.key}); @override State<DarkestWorldLiveDetailChamber> createState()=>_DarkestWorldLiveDetailChamberState(); }
class _DarkestWorldLiveDetailChamberState extends State<DarkestWorldLiveDetailChamber> with SingleTickerProviderStateMixin{
 final session=GalaxyNavigationSession.instance; late final AnimationController clock=AnimationController(vsync:this,duration:const Duration(seconds:88))..repeat();
 @override void initState(){super.initState();session.addListener(_changed);} void _changed(){if(mounted)setState((){});} @override void dispose(){session.removeListener(_changed);clock.dispose();super.dispose();}
 @override Widget build(BuildContext context){final nav=session.contentNavigation;if(nav==null)return const SizedBox.shrink();final compact=MediaQuery.sizeOf(context).width<900;return IgnorePointer(child:AnimatedBuilder(animation:clock,builder:(_,__)=>SizedBox.expand(child:Padding(padding:EdgeInsets.fromLTRB(compact?10:28,compact?82:105,compact?10:28,compact?76:112),child:Align(alignment:Alignment.center,child:Container(constraints:const BoxConstraints(maxWidth:1450),height:compact?300:410,decoration:BoxDecoration(color:const Color(0xE4050610),border:Border.all(color:const Color(0x327F70B0)),boxShadow:const[BoxShadow(color:Colors.black87,blurRadius:35)]),child:Stack(children:[Positioned.fill(child:CustomPaint(painter:_LivePainter(clock.value))),Padding(padding:EdgeInsets.all(compact?16:28),child:compact?_Compact(nav:nav):_Wide(nav:nav)),const Positioned(left:12,top:10,child:_Tag('ARCHIVE DETAIL CHAMBER')),const Positioned(right:12,top:10,child:_Tag('LIVE SELECTION'))])))))));}
}
class _Wide extends StatelessWidget{final DarkestWorldNavigationState nav;const _Wide({required this.nav});@override Widget build(BuildContext c)=>Row(children:[Expanded(flex:5,child:_Object(title:nav.current.title)),Expanded(flex:7,child:Padding(padding:const EdgeInsets.only(left:28),child:_Data(nav:nav)))]);}
class _Compact extends StatelessWidget{final DarkestWorldNavigationState nav;const _Compact({required this.nav});@override Widget build(BuildContext c)=>Row(children:[Expanded(child:_Object(title:nav.current.title)),Expanded(child:_Data(nav:nav))]);}
class _Object extends StatelessWidget{final String title;const _Object({required this.title});@override Widget build(BuildContext c)=>Center(child:Container(width:180,height:230,decoration:BoxDecoration(color:const Color(0xD90B0D15),border:Border.all(color:const Color(0x687C708F)),boxShadow:const[BoxShadow(color:Colors.black87,blurRadius:25,offset:Offset(12,18))]),child:Stack(children:[Positioned.fill(child:CustomPaint(painter:_ObjectPainter())),Center(child:Padding(padding:const EdgeInsets.all(18),child:Text(title.toUpperCase(),textAlign:TextAlign.center,maxLines:5,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:12,letterSpacing:1.5,fontWeight:FontWeight.w300))))]));}
class _Data extends StatelessWidget{final DarkestWorldNavigationState nav;const _Data({required this.nav});@override Widget build(BuildContext c)=>Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('CURRENT ARCHIVE OBJECT',style:TextStyle(fontSize:7,letterSpacing:3,color:Color(0x7897A8BE))),const SizedBox(height:12),Text(nav.current.title.toUpperCase(),maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:26,letterSpacing:1.8,fontWeight:FontWeight.w300)),const SizedBox(height:20),_Line('ENTRY',nav.entryLabel),_Line('SOURCE',nav.source.toUpperCase()),_Line('PREVIOUS',nav.previous?.title??'—'),_Line('NEXT',nav.next?.title??'—'),_Line('RELATED','${nav.related.length} WORLDS'),const SizedBox(height:16),const Text('OBJECT STATUS  /  STABLE',style:TextStyle(fontSize:6.5,letterSpacing:1.8,color:Color(0x667F90A4)))]);}
class _Line extends StatelessWidget{final String a,b;const _Line(this.a,this.b);@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.only(bottom:7),child:Row(children:[SizedBox(width:72,child:Text(a,style:const TextStyle(fontSize:5.5,letterSpacing:1.2,color:Color(0x557F90A4)))),Expanded(child:Text(b,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:7.5,letterSpacing:1)))]));}
class _Tag extends StatelessWidget{final String t;const _Tag(this.t);@override Widget build(BuildContext c)=>DecoratedBox(decoration:const BoxDecoration(color:Color(0xD805060D)),child:Padding(padding:const EdgeInsets.symmetric(horizontal:8,vertical:5),child:Text(t,style:const TextStyle(fontSize:5.5,letterSpacing:1.7,color:Color(0x667F8EA2)))));}
class _LivePainter extends CustomPainter{final double p;const _LivePainter(this.p);@override void paint(Canvas c,Size s){final r=Offset.zero&s;c.drawRect(r,Paint()..shader=const RadialGradient(center:Alignment(-.2,0),radius:1.2,colors:[Color(0xFF241D32),Color(0xFF080912),Color(0xFF020207)]).createShader(r));final center=Offset(s.width*.27,s.height*.5);final pen=Paint()..style=PaintingStyle.stroke..strokeWidth=.55..color=const Color(0x247F90A4);for(var i=0;i<7;i++){final d=50+i*22.0;c.drawOval(Rect.fromCenter(center:center,width:d*2.4,height:d*.72),pen);}final a=p*math.pi*2;c.drawArc(Rect.fromCenter(center:center,width:300,height:100),a,.9,false,Paint()..style=PaintingStyle.stroke..strokeWidth=1.1..color=const Color(0x657D91A5));final scan=(p*s.height*1.6)%s.height;c.drawRect(Rect.fromLTWH(0,scan,s.width,1),Paint()..color=const Color(0x147F70B0));c.drawRect(r,Paint()..shader=RadialGradient(center:Alignment.center,radius:1.1,colors:[const Color(0x00000000),const Color(0x90000000)]).createShader(r));} @override bool shouldRepaint(covariant _LivePainter old)=>old.p!=p;}
class _ObjectPainter extends CustomPainter{@override void paint(Canvas c,Size s){final r=Offset.zero&s;c.drawRect(r,Paint()..shader=const LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:[Color(0x188F82A9),Color(0x00000000)]).createShader(r));c.drawLine(Offset(0,s.height*.76),Offset(s.width,s.height*.76),Paint()..color=const Color(0x207F90A4));} @override bool shouldRepaint(covariant _ObjectPainter old)=>false;}
