import 'dart:math' as math;
import 'package:flutter/material.dart';

enum GalaxyWorldKind { vegeta, game, identity, cinema, creation, music, family, archive, comingSoon }
class GalaxyWorld { final GalaxyWorldKind kind; final String title,description; const GalaxyWorld({required this.kind,required this.title,required this.description}); }
class DarkestWorldUniverse extends StatefulWidget { final List<GalaxyWorld> worlds; final ValueChanged<GalaxyWorld>? onWorldTap; const DarkestWorldUniverse({super.key,required this.worlds,this.onWorldTap}); @override State<DarkestWorldUniverse> createState()=>_DarkestWorldUniverseState(); }
class _DarkestWorldUniverseState extends State<DarkestWorldUniverse> with SingleTickerProviderStateMixin {
 GalaxyWorldKind? selected; late final AnimationController clock=AnimationController(vsync:this,duration:const Duration(seconds:36))..repeat(); @override void dispose(){clock.dispose();super.dispose();}
 @override Widget build(BuildContext context){final compact=MediaQuery.sizeOf(context).width<760;GalaxyWorld? current;for(final w in widget.worlds){if(w.kind==selected){current=w;break;}}return Scaffold(backgroundColor:const Color(0xFF010106),body:AnimatedBuilder(animation:clock,builder:(_,__)=>Stack(children:[Positioned.fill(child:CustomPaint(painter:_UniversePainter(clock.value))),Positioned(left:compact?18:34,top:compact?18:28,child:const Text('DARKESTWORLD',style:TextStyle(fontSize:14,letterSpacing:5,fontWeight:FontWeight.w300))),Center(child:SizedBox(width:compact?360:900,height:compact?520:700,child:Stack(children:[for(var i=0;i<widget.worlds.length;i++)_Planet(world:widget.worlds[i],index:i,total:widget.worlds.length,t:clock.value,selected:selected==widget.worlds[i].kind,compact:compact,onTap:()=>setState(()=>selected=selected==widget.worlds[i].kind?null:widget.worlds[i].kind))]))),if(current!=null)Positioned(left:compact?14:34,right:compact?14:34,bottom:compact?14:28,child:_Panel(world:current,compact:compact,onClose:()=>setState(()=>selected=null),onEnter:()=>widget.onWorldTap?.call(current!))) ])));}
}
class _Planet extends StatelessWidget { final GalaxyWorld world;final int index,total;final double t;final bool selected,compact;final VoidCallback onTap;const _Planet({required this.world,required this.index,required this.total,required this.t,required this.selected,required this.compact,required this.onTap}); @override Widget build(BuildContext context){final a=-math.pi/2+index*math.pi*2/math.max(1,total)+t*.30;final orbit=compact?145.0:270.0,center=Offset(compact?180:450,compact?260:350);final p=Offset(center.dx+math.cos(a)*orbit*.72,center.dy+math.sin(a)*orbit*.55);final size=selected?(compact?112.0:152.0):(compact?80.0:112.0);return Positioned(left:p.dx-size/2,top:p.dy-size/2,child:GestureDetector(onTap:onTap,child:Column(children:[Container(width:size,height:size,decoration:BoxDecoration(shape:BoxShape.circle,gradient:const RadialGradient(center:Alignment(-.34,-.38),radius:.9,colors:[Color(0xFF8D86A7),Color(0xFF353047),Color(0xFF080810)]),border:Border.all(color:Colors.white.withValues(alpha:selected?.34:.12)),boxShadow:selected?const[BoxShadow(color:Color(0x557F70B0),blurRadius:42,spreadRadius:3)]:const[]),child:CustomPaint(painter:_PlanetPainter(index,selected,t))),const SizedBox(height:8),Text(world.title,style:TextStyle(fontSize:selected?10:7,letterSpacing:2.2,color:Colors.white.withValues(alpha:selected?.9:.45)))])));}}
class _Panel extends StatelessWidget { final GalaxyWorld world;final bool compact;final VoidCallback onClose,onEnter;const _Panel({required this.world,required this.compact,required this.onClose,required this.onEnter});@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:const Color(0xEE080812),borderRadius:BorderRadius.circular(18),border:Border.all(color:const Color(0x557F70B0))),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(world.title.toUpperCase(),style:const TextStyle(fontSize:14,letterSpacing:3)),const SizedBox(height:5),Text(world.description,style:const TextStyle(fontSize:8,color:Colors.white38))])),if(!compact)TextButton(onPressed:onClose,child:const Text('CLOSE')),FilledButton(onPressed:onEnter,child:const Text('ENTER'))]));}
class _UniversePainter extends CustomPainter { final double t;const _UniversePainter(this.t);@override void paint(Canvas c,Size s){final r=Offset.zero&s;c.drawRect(r,Paint()..shader=const RadialGradient(center:Alignment(0,-.05),radius:1.15,colors:[Color(0xFF211B39),Color(0xFF080711),Color(0xFF010105)]).createShader(r));final q=math.Random(417);for(var i=0;i<360;i++){final x=(q.nextDouble()*s.width+t*s.width*.018)%s.width,y=q.nextDouble()*s.height;c.drawCircle(Offset(x,y),.15+q.nextDouble()*.7,Paint()..color=Colors.white.withValues(alpha:.012+q.nextDouble()*.05));}final cx=s.width*.5,cy=s.height*.49;for(var k=0;k<7;k++){c.drawOval(Rect.fromCenter(center:Offset(cx,cy),width:s.width*(.52+k*.065),height:s.height*(.60+k*.065)),Paint()..style=PaintingStyle.stroke..strokeWidth=k==0?1.1:.45..color=const Color(0x129A8CC0));}}
@override bool shouldRepaint(covariant _UniversePainter old)=>old.t!=t;}
class _PlanetPainter extends CustomPainter { final int seed;final bool active;final double t;const _PlanetPainter(this.seed,this.active,this.t);@override void paint(Canvas c,Size s){final rnd=math.Random(seed*731+19),center=Offset(s.width*.47,s.height*.45),rad=s.shortestSide*.475;final globe=Paint()..shader=const RadialGradient(center:Alignment(-.36,-.4),radius:1,colors:[Color(0xFF77718C),Color(0xFF332E43),Color(0xFF050509)]).createShader(Offset.zero&s);c.drawCircle(center,rad,globe);final ocean=Paint()..color=const Color(0x183B3650);c.drawCircle(center,rad*.96,ocean);final land=Paint()..style=PaintingStyle.fill..color=const Color(0x405F5A70);final ridge=Paint()..style=PaintingStyle.stroke..strokeWidth=active?.8:.55..color=Colors.white.withValues(alpha:active?.15:.065);for(var n=0;n<11;n++){final a=rnd.nextDouble()*math.pi*2,rr=rad*(.18+rnd.nextDouble()*.26),b=Offset(center.dx+math.cos(a)*rad*.46,center.dy+math.sin(a)*rad*.38);final path=Path();for(var j=0;j<14;j++){final ang=j*math.pi*2/14,scale=.55+rnd.nextDouble()*.7,pt=Offset(b.dx+math.cos(ang)*rr*scale,b.dy+math.sin(ang)*rr*scale*.52);if(j==0)path.moveTo(pt.dx,pt.dy);else path.lineTo(pt.dx,pt.dy);}path.close();c.drawPath(path,land);for(var k=1;k<4;k++){final inset=k*rad*.018;c.drawPath(path.shift(Offset(-inset*.2,-inset*.15)),ridge);}}
for(var i=0;i<35;i++){final x=center.dx+(rnd.nextDouble()-.5)*rad*1.7,y=center.dy+(rnd.nextDouble()-.5)*rad*1.7;c.drawCircle(Offset(x,y),.3+rnd.nextDouble()*1.2,ridge);}final shade=Paint()..shader=const LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:[Colors.transparent,Color(0x18000000),Color(0xB5000000)]).createShader(Offset.zero&s);c.drawCircle(center,rad,shade);final atmosphere=Paint()..style=PaintingStyle.stroke..strokeWidth=active?2.2:1.3..color=Colors.white.withValues(alpha:active?.13:.07);c.drawCircle(center,rad+1.5,atmosphere);c.drawArc(Rect.fromCircle(center:center,radius:rad+2),math.pi*1.02,math.pi*.52,false,Paint()..style=PaintingStyle.stroke..strokeWidth=1.3..color=Color(0x357F70B0));final pulse=.02+.018*math.sin(t*math.pi*2+seed);c.drawArc(Rect.fromCircle(center:center,radius:rad*.97),math.pi*1.03,math.pi*.45,false,Paint()..style=PaintingStyle.stroke..strokeWidth=.8..color=Colors.white.withValues(alpha:pulse));}
@override bool shouldRepaint(covariant _PlanetPainter old)=>old.seed!=seed||old.active!=active||old.t!=t;}
