import 'package:flutter/material.dart';
import '../core/content_models.dart';
import '../core/content_repository.dart';
import '../core/supabase_client.dart';
import 'content_detail_page.dart';

class ContentBrowserPage extends StatefulWidget { final String? contentType; final String title; final List<int> platformIds; const ContentBrowserPage({super.key, required this.title, this.contentType, this.platformIds = const []}); @override State<ContentBrowserPage> createState() => _ContentBrowserPageState(); }
class _ContentBrowserPageState extends State<ContentBrowserPage> {
  final repository = ContentRepository(); final items = <ContentItem>[]; bool loading = true; String query = '';
  bool get snes => widget.contentType == 'game' && (widget.platformIds.contains(19) || widget.title.toUpperCase().contains('SNES'));
  @override void initState() { super.initState(); load(); }
  Future<void> load() async { try { List<ContentItem> result; if (snes) { final rows = await supabase.from('storage_assets').select('id,title,public_url,metadata').eq('asset_type','snes_sealed').not('public_url','is',null).neq('public_url','').order('title').limit(1000); result = [for (final row in rows) _snes(Map<String,dynamic>.from(row))]; } else { result = await repository.getContentItemsPage(type: widget.contentType, page: 0); } if (mounted) setState(() { items.addAll(result); loading = false; }); } catch (_) { if (mounted) setState(() => loading = false); } }
  ContentItem _snes(Map<String,dynamic> row) { final meta = row['metadata'] is Map ? Map<String,dynamic>.from(row['metadata']) : <String,dynamic>{}; meta['public_url'] = row['public_url']; return ContentItem.fromRow({'id':'snes:${row['id']}','content_type':'game','title':'${row['title'] ?? 'Untitled'}','slug':'snes-${row['id']}','metadata':meta}); }
  @override Widget build(BuildContext context) { final shown = items.where((x) => query.isEmpty || x.title.toLowerCase().contains(query.toLowerCase())).toList(); return Scaffold(backgroundColor: const Color(0xFF010107), body: Stack(children: [const Positioned.fill(child: _ArchiveBackground()), SafeArea(child: Padding(padding: const EdgeInsets.all(18), child: Column(children: [Row(children: [IconButton(onPressed: () => Navigator.pop(context), icon: const Icon(Icons.arrow_back_ios_new, size: 16)), Expanded(child: Text(widget.title.toUpperCase(), style: const TextStyle(fontSize: 12, letterSpacing: 2.5))), SizedBox(width: 220, height: 34, child: TextField(onChanged: (v) => setState(() => query = v), style: const TextStyle(fontSize: 10), decoration: const InputDecoration(hintText:'SEARCH ARCHIVE', prefixIcon: Icon(Icons.search, size:14))))]), const SizedBox(height: 12), Expanded(child: loading ? const Center(child: CircularProgressIndicator()) : shown.isEmpty ? const Center(child: Text('GEEN CONTENT', style: TextStyle(letterSpacing: 3, color: Colors.white38))) : GridView.builder(gridDelegate: const SliverGridDelegateWithMaxCrossAxisExtent(maxCrossAxisExtent: 230, mainAxisExtent: 310, crossAxisSpacing: 12, mainAxisSpacing: 12), itemCount: shown.length, itemBuilder: (_, i) { final item = shown[i]; final url = '${item.metadata['public_url'] ?? item.metadata['image_url'] ?? ''}'; return GestureDetector(onTap: () => Navigator.of(context).push(MaterialPageRoute(builder: (_) => ContentDetailPage(item:item))), child: Container(decoration: BoxDecoration(color: const Color(0xFF080811), borderRadius: BorderRadius.circular(14), border: Border.all(color: Colors.white.withValues(alpha:.08))), child: Column(children: [Expanded(child: url.isEmpty ? Center(child: Padding(padding: const EdgeInsets.all(18), child: Text(item.title, textAlign: TextAlign.center))) : Image.network(url, fit: BoxFit.cover, width: double.infinity, errorBuilder: (_, __, ___) => Center(child: Text(item.title, textAlign: TextAlign.center)))), Padding(padding: const EdgeInsets.all(10), child: Text(item.title, maxLines: 2, overflow: TextOverflow.ellipsis))]))); })), ])))])); }
}
class _ArchiveBackground extends StatelessWidget { const _ArchiveBackground(); @override Widget build(BuildContext context) => CustomPaint(painter:_ArchivePainter()); }
class _ArchivePainter extends CustomPainter { @override void paint(Canvas c, Size s) { c.drawRect(Offset.zero & s, Paint()..shader = const RadialGradient(colors:[Color(0xFF19152B),Color(0xFF07070F),Color(0xFF010106)]).createShader(Offset.zero & s)); } @override bool shouldRepaint(covariant _ArchivePainter old) => false; }
