import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'game_list_page.dart';

class GamePlatformPage extends StatefulWidget { final String territory; final List<GamePlatformGroup> groups; const GamePlatformPage({super.key, required this.territory, required this.groups}); @override State<GamePlatformPage> createState() => _GamePlatformPageState(); }
class _GamePlatformPageState extends State<GamePlatformPage> with SingleTickerProviderStateMixin { int? selected; late final AnimationController clock = AnimationController(vsync: this, duration: const Duration(seconds: 30))..repeat(); List<GamePlatform> get platforms => widget.groups.expand((g) => g.platforms).toList(); @override void dispose() { clock.dispose(); super.dispose(); } void open(int i) { final p = platforms[i]; Navigator.of(context).push(MaterialPageRoute(builder: (_) => GameListPage(territory: widget.territory, platform: p.name, externalPlatformIds: p.externalPlatformIds, navigationPlatforms: platforms, navigationIndex: i))); }
@override Widget build(BuildContext context) => Scaffold(backgroundColor: const Color(0xFF010208), body: AnimatedBuilder(animation: clock, builder: (_, __) => Stack(children: [Positioned.fill(child: CustomPaint(painter: _PlatformSpace(clock.value))), SafeArea(child: Padding(padding: const EdgeInsets.all(20), child: Row(children: [IconButton(onPressed: () => Navigator.pop(context), icon: const Icon(Icons.arrow_back_ios_new, size: 16)), Text('${widget.territory.toUpperCase()} / PLATFORM WORLDS', style: const TextStyle(fontSize: 10, letterSpacing: 2.5)), const Spacer(), Text('${platforms.length} WORLDS', style: const TextStyle(fontSize: 7, letterSpacing: 2, color: Colors.white24))]))), Center(child: LayoutBuilder(builder: (_, box) { final d = math.min(box.maxWidth * .88, box.maxHeight * .72); return SizedBox(width: d, height: d, child: Stack(children: [for (var i = 0; i < platforms.length; i++) _Node(platform: platforms[i], index: i, total: platforms.length, selected: selected == i, size: d, onTap: () => setState(() => selected = selected == i ? null : i), onOpen: () => open(i))])); })), if (selected != null) Positioned(left: 20, right: 20, bottom: 20, child: _Panel(platform: platforms[selected!], index: selected!, total: platforms.length, onClose: () => setState(() => selected = null), onOpen: () => open(selected!))) ])));
}
class GamePlatformGroup { final String name; final String subtitle; final List<GamePlatform> platforms; const GamePlatformGroup(this.name, this.subtitle, this.platforms); }
class GamePlatform { final String name; final List<int> externalPlatformIds; const GamePlatform(this.name, this.externalPlatformIds); }
class _Node extends StatelessWidget { final GamePlatform platform; final int index,total; final bool selected; final double size; final VoidCallback onTap,onOpen; const _Node({required this.platform,required this.index,required this.total,required this.selected,required this.size,required this.onTap,required this.onOpen}); @override Widget build(BuildContext context) { final a = -math.pi/2 + index * math.pi * 2 / math.max(1,total); final c = size/2; final radius = size*.33; final p = Offset(c + math.cos(a)*radius, c + math.sin(a)*radius); final s = selected ? 120.0 : 92.0; return Positioned(left:p.dx-s/2,top:p.dy-s/2,child:GestureDetector(onTap:onTap,child:Column(children:[Container(width:s,height:s,decoration:BoxDecoration(shape:BoxShape.circle,gradient:const RadialGradient(colors:[Color(0xFF81769A),Color(0xFF2D273E),Color(0xFF030307)]),border:Border.all(color:Colors.white.withValues(alpha:selected?.30:.10)),boxShadow:selected?const[BoxShadow(color:Color(0x557F70B0),blurRadius:30)]:const[]),child:CustomPaint(painter:_NodeRelief(index))),const SizedBox(height:6),Text(platform.name,style:TextStyle(fontSize:selected?9:7,letterSpacing:1.7,color:Colors.white.withValues(alpha:selected?.9:.45)))]))); } }
class _NodeRelief extends CustomPainter { final int seed; const _NodeRelief(this.seed); @override void paint(Canvas c,Size s){final p=Paint()..style=PaintingStyle.stroke..strokeWidth=.7..color=const Color(0x557F7394);for(var i=0;i<5;i++)c.drawOval(Rect.fromCenter(center:s.center,width:s.width*(.35+i*.12),height:s.height*(.18+i*.1)),p);} @override bool shouldRepaint(covariant _NodeRelief old)=>false; }
class _Panel extends StatelessWidget { final GamePlatform platform; final int index,total; final VoidCallback onClose,onOpen; const _Panel({required this.platform,required this.index,required this.total,required this.onClose,required this.onOpen}); @override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:const Color(0xEE080812),borderRadius:BorderRadius.circular(16),border:Border.all(color:const Color(0x557F70B0))),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(platform.name,style:const TextStyle(fontSize:13,letterSpacing:2.5)),const SizedBox(height:4),Text('PLATFORM WORLD  •  ${index+1}/$total',style:const TextStyle(fontSize:7,color:Colors.white38))])),TextButton(onPressed:onClose,child:const Text('CLOSE')),FilledButton(onPressed:onOpen,child:const Text('ENTER'))])); }
class _PlatformSpace extends CustomPainter { final double t; const _PlatformSpace(this.t); @override void paint(Canvas c,Size s){final r=math.Random(412);c.drawRect(Offset.zero&s,Paint()..shader=const RadialGradient(colors:[Color(0xFF19152B),Color(0xFF07070F),Color(0xFF010106)]).createShader(Offset.zero&s));for(var i=0;i<300;i++)c.drawCircle(Offset((r.nextDouble()*s.width+t*s.width*.02)%s.width,r.nextDouble()*s.height),.2+r.nextDouble()*.7,Paint()..color=Colors.white.withValues(alpha:.02));} @override bool shouldRepaint(covariant _PlatformSpace old)=>old.t!=t; }
