import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'game_list_page.dart';

class GamePlatformPage extends StatefulWidget {
  final String territory;
  final List<GamePlatformGroup> groups;
  const GamePlatformPage({super.key, required this.territory, required this.groups});
  @override State<GamePlatformPage> createState() => _GamePlatformPageState();
}
class _GamePlatformPageState extends State<GamePlatformPage> with SingleTickerProviderStateMixin {
  late final AnimationController clock = AnimationController(vsync: this, duration: const Duration(seconds: 100))..repeat();
  int? selected;
  List<GamePlatform> get platforms => widget.groups.expand((g) => g.platforms).toList(growable: false);
  @override void dispose() { clock.dispose(); super.dispose(); }
  void enter(int index) { final p = platforms[index]; Navigator.of(context).push(MaterialPageRoute(builder: (_) => GameListPage(territory: widget.territory, platform: p.name, externalPlatformIds: p.externalPlatformIds, navigationPlatforms: platforms, navigationIndex: index))); }
  @override Widget build(BuildContext context) {
    final size = MediaQuery.sizeOf(context); final compact = size.width < 820;
    return Scaffold(backgroundColor: const Color(0xFF01030A), body: AnimatedBuilder(animation: clock, builder: (_, __) => Stack(fit: StackFit.expand, children: [
      CustomPaint(painter: _Space(clock.value)),
      SafeArea(child: Padding(padding: EdgeInsets.all(compact ? 14 : 30), child: Row(children: [IconButton(onPressed: () => Navigator.pop(context), icon: const Icon(Icons.arrow_back_ios_new, size: 14)), const SizedBox(width: 8), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('${widget.territory.toUpperCase()} / PLATFORM WORLDS', style: const TextStyle(fontSize: 11, letterSpacing: 3.2)), const Text('GENERATIONAL ARCHIVE / ORBITAL SYSTEM', style: TextStyle(fontSize: 6.5, letterSpacing: 2.4, color: Color(0x55FFFFFF)))])), Text('${platforms.length.toString().padLeft(2, '0')} WORLDS', style: const TextStyle(fontSize: 7, letterSpacing: 2, color: Color(0x66FFFFFF)))]))),
      Center(child: LayoutBuilder(builder: (_, box) { final d = math.min(box.maxWidth * (compact ? .98 : .84), box.maxHeight * (compact ? .72 : .80)).toDouble(); return SizedBox.square(dimension: d, child: Stack(children: [CustomPaint(size: Size(d, d), painter: _Orbits(clock.value)), for (var i = 0; i < platforms.length; i++) _Node(platform: platforms[i], index: i, total: platforms.length, selected: selected == i, diameter: d, phase: clock.value, onTap: () => setState(() => selected = selected == i ? null : i), onOpen: () => enter(i)), const Center(child: IgnorePointer(child: _Core()))])); })),
      Positioned(left: compact ? 12 : 30, right: compact ? 12 : 30, bottom: compact ? 14 : 28, child: selected == null ? const Center(child: Text('1× CLICK FOCUS    2× CLICK ENTER PLATFORM', style: TextStyle(fontSize: 6.5, letterSpacing: 1.8, color: Color(0x55FFFFFF)))) : _Panel(platform: platforms[selected!], index: selected!, total: platforms.length, onClose: () => setState(() => selected = null), onOpen: () => enter(selected!))),
    ])));
  }
}
class GamePlatformGroup { final String name; final String subtitle; final List<GamePlatform> platforms; const GamePlatformGroup(this.name, this.subtitle, this.platforms); }
class GamePlatform { final String name; final List<int> externalPlatformIds; const GamePlatform(this.name, this.externalPlatformIds); }
class _Node extends StatelessWidget {
  final GamePlatform platform; final int index, total; final bool selected; final double diameter, phase; final VoidCallback onTap, onOpen;
  const _Node({required this.platform, required this.index, required this.total, required this.selected, required this.diameter, required this.phase, required this.onTap, required this.onOpen});
  @override Widget build(BuildContext context) { final c = diameter / 2; final orbit = diameter * (.19 + (index % 5) * .065); final angle = -math.pi / 2 + index * math.pi * 2 / math.max(1, total) + phase * math.pi * .22 * (index.isEven ? 1 : -1); final p = Offset(c + math.cos(angle) * orbit, c + math.sin(angle) * orbit); final node = (selected ? math.max(72, diameter * .112) : math.max(52, diameter * .073)).toDouble(); return Positioned(left: p.dx - node / 2, top: p.dy - node / 2, width: node, height: node, child: GestureDetector(onTap: onTap, onDoubleTap: onOpen, child: CustomPaint(painter: _World(seed: index, selected: selected, phase: phase)))); }
}
class _World extends CustomPainter { final int seed; final bool selected; final double phase; const _World({required this.seed, required this.selected, required this.phase}); @override void paint(Canvas c, Size s) { final center = s.center(Offset.zero); final r = s.width * .36; final rect = Rect.fromCircle(center: center, radius: r); final base = Color([0xFF8B7A6D, 0xFF647B87, 0xFF8C927E, 0xFF7D6F83, 0xFF718A86][seed % 5]); c.drawCircle(center, r * 1.35, Paint()..shader = RadialGradient(colors: [const Color(0x448FA8B8), Colors.transparent]).createShader(Rect.fromCircle(center: center, radius: r * 1.35))); c.drawCircle(center, r, Paint()..shader = RadialGradient(center: const Alignment(-.42, -.5), colors: [base, base.withValues(alpha: .72), const Color(0xFF25303A), const Color(0xFF03050A)]).createShader(rect)); c.drawCircle(center, r, Paint()..style = PaintingStyle.stroke..strokeWidth = selected ? 1.3 : .7..color = const Color(0x709AAEBC)); if (selected) c.drawArc(Rect.fromCircle(center: center, radius: r * 1.2), phase * math.pi * 2, 1.2, false, Paint()..style = PaintingStyle.stroke..strokeWidth = 1..color = const Color(0x889FB7C5)); }
  @override bool shouldRepaint(covariant _World old) => old.seed != seed || old.selected != selected || old.phase != phase;
}
class _Orbits extends CustomPainter { final double phase; const _Orbits(this.phase); @override void paint(Canvas c, Size s) { final center = s.center(Offset.zero); for (var i = 0; i < 7; i++) { final r = s.shortestSide * (.18 + i * .052); c.drawOval(Rect.fromCenter(center: center, width: r * 2, height: r * 1.15), Paint()..style = PaintingStyle.stroke..strokeWidth = i == 6 ? .9 : .45..color = const Color(0x1F90A7B7)); } c.drawArc(Rect.fromCenter(center: center, width: s.width * .84, height: s.height * .48), phase * math.pi * 2, .65, false, Paint()..style = PaintingStyle.stroke..strokeWidth = 1.1..color = const Color(0x507F9AAC)); }
  @override bool shouldRepaint(covariant _Orbits old) => old.phase != phase;
}
class _Core extends StatelessWidget { const _Core(); @override Widget build(BuildContext context) => Container(width: 58, height: 58, decoration: const BoxDecoration(shape: BoxShape.circle, gradient: RadialGradient(colors: [Color(0xFFFFFFFF), Color(0xFFD4C4A4), Color(0xFF695A48), Color(0x00000000)], stops: [0, .2, .48, 1]), boxShadow: [BoxShadow(color: Color(0x668F7B5D), blurRadius: 30, spreadRadius: 8)])); }
class _Panel extends StatelessWidget { final GamePlatform platform; final int index, total; final VoidCallback onClose, onOpen; const _Panel({required this.platform, required this.index, required this.total, required this.onClose, required this.onOpen}); @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.all(14), decoration: BoxDecoration(color: const Color(0xF2070B12), border: Border.all(color: const Color(0x527E98A9))), child: Row(children: [Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('PLATFORM WORLD / ${index + 1}/$total', style: const TextStyle(fontSize: 6.5, letterSpacing: 1.8, color: Color(0x62FFFFFF))), const SizedBox(height: 5), Text(platform.name, style: const TextStyle(fontSize: 16, letterSpacing: 2.8))])), TextButton(onPressed: onClose, child: const Text('×')), FilledButton(onPressed: onOpen, child: const Text('ENTER ARCHIVE'))])); }
class _Space extends CustomPainter { final double phase; const _Space(this.phase); @override void paint(Canvas c, Size s) { final r = Offset.zero & s; c.drawRect(r, Paint()..shader = const RadialGradient(colors: [Color(0xFF0C1420), Color(0xFF030711), Color(0xFF010207)]).createShader(r)); final rnd = math.Random(1188); for (var i = 0; i < 420; i++) { final p = Offset(rnd.nextDouble() * s.width, rnd.nextDouble() * s.height); c.drawCircle(p, .25 + rnd.nextDouble() * .7, Paint()..color = Colors.white.withValues(alpha: .025 + .1 * ((math.sin(phase * math.pi * 2 + i) + 1) / 2))); } } @override bool shouldRepaint(covariant _Space old) => old.phase != phase; }