import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'game_platform_page.dart';

class GameWorldPlanetPage extends StatefulWidget {
  const GameWorldPlanetPage({super.key});
  @override State<GameWorldPlanetPage> createState() => _GameWorldPlanetPageState();
}
class _TerritoryData {
  final String name, description;
  final List<GamePlatformGroup> groups;
  const _TerritoryData(this.name, this.description, this.groups);
}
class _GameWorldPlanetPageState extends State<GameWorldPlanetPage> with SingleTickerProviderStateMixin {
  int? selected;
  late final AnimationController _controller=AnimationController(vsync:this,duration:const Duration(seconds:18))..repeat();
  final territories=< _TerritoryData>[
    _TerritoryData('NINTENDO','Nintendo generations.',[GamePlatformGroup('HOME CONSOLES','Home generations.',[GamePlatform('NES',[18]),GamePlatform('SNES',[19]),GamePlatform('N64',[4]),GamePlatform('GameCube',[21]),GamePlatform('Wii',[5]),GamePlatform('Wii U',[41]),GamePlatform('Switch',[130])]),GamePlatformGroup('HANDHELD','Portable generations.',[GamePlatform('Game Boy',[33]),GamePlatform('Game Boy Color',[22]),GamePlatform('Game Boy Advance',[24]),GamePlatform('DS',[20]),GamePlatform('3DS',[37])])]),
    _TerritoryData('SEGA','Sega generations.',[GamePlatformGroup('CONSOLES','Console generations.',[GamePlatform('Master System',[64]),GamePlatform('Mega Drive',[29]),GamePlatform('Saturn',[32]),GamePlatform('Dreamcast',[23])]),GamePlatformGroup('PORTABLE','Portable generation.',[GamePlatform('Game Gear',[35])])]),
    _TerritoryData('PLAYSTATION','PlayStation generations.',[GamePlatformGroup('GENERATIONS','Main generations.',[GamePlatform('PlayStation',[7]),GamePlatform('PlayStation 2',[8]),GamePlatform('PlayStation 3',[9]),GamePlatform('PlayStation 4',[48]),GamePlatform('PlayStation 5',[167])])]),
    _TerritoryData('XBOX','Xbox generations.',[GamePlatformGroup('GENERATIONS','Main generations.',[GamePlatform('Xbox',[11]),GamePlatform('Xbox 360',[12]),GamePlatform('Xbox One',[49]),GamePlatform('Xbox Series',[169])])]),
  ];
  @override void dispose(){_controller.dispose();super.dispose();}
  void enter(int i)=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>GamePlatformPage(territory:territories[i].name,groups:territories[i].groups)));
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFF010207),body:LayoutBuilder(builder:(context,b){final compact=b.maxWidth<760;final d=math.min(b.maxWidth*.92,b.maxHeight*.88);return AnimatedBuilder(animation:_controller,builder:(context,_){return Stack(children:[Positioned.fill(child:CustomPaint(painter:_SpacePainter(t:_controller.value))),SafeArea(child:Padding(padding:EdgeInsets.all(compact?14:28),child:Row(children:[IconButton(onPressed:()=>Navigator.of(context).pop(),icon:const Icon(Icons.arrow_back_ios_new,size:16)),const SizedBox(width:8),const Text('GAME-WORLD',style:TextStyle(fontSize:16,letterSpacing:4)),const Spacer(),Text('ONE WORLD  •  FOUR REGIONS',style:TextStyle(fontSize:8,letterSpacing:2.4,color:Colors.white24))]))),Center(child:SizedBox(width:d,height:d,child:GestureDetector(onTapUp:(e){final i=_hit(e.localPosition,d,_controller.value);if(i!=null)setState(()=>selected=selected==i?null:i);},child:CustomPaint(painter:_PlanetPainter(selected:selected,rotation:_controller.value),child:Stack(children:[_label('NINTENDO',.25,.23,0,d),_label('SEGA',.74,.29,1,d),_label('PLAYSTATION',.27,.72,2,d),_label('XBOX',.74,.65,3,d),Center(child:Opacity(opacity:selected==null?1:.08,child:const Text('GAME-WORLD',style:TextStyle(fontSize:12,letterSpacing:5,color:Colors.white38))))]))))),if(selected!=null)Positioned(left:compact?14:30,right:compact?14:30,bottom:compact?42:54,child:Center(child:Container(padding:const EdgeInsets.symmetric(horizontal:18,vertical:15),constraints:const BoxConstraints(maxWidth:640),decoration:BoxDecoration(color:const Color(0xE6090914),borderRadius:BorderRadius.circular(18),border:Border.all(color:const Color(0x447F70B0)),boxShadow:const[BoxShadow(color:Color(0x66000000),blurRadius:30,offset:Offset(0,12))]),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(territories[selected!].name,style:const TextStyle(fontSize:14,letterSpacing:3)),const SizedBox(height:5),Text(territories[selected!].description,style:const TextStyle(fontSize:9,color:Colors.white38))])),TextButton(onPressed:()=>enter(selected!),child:const Text('ENTER'))])))),Positioned(left:compact?16:30,bottom:compact?16:24,child:Text(selected==null?'SELECT A REGION':'REGION SELECTED  •  ENTER TO OPEN',style:const TextStyle(fontSize:8,letterSpacing:2.5,color:Colors.white24)))];});}));
  Widget _label(String text,double x,double y,int i,double d){final a=selected==null||selected==i?.82:.06;return Positioned(left:d*x-100,top:d*y-22,width:200,child:IgnorePointer(child:Center(child:Text(text,style:TextStyle(fontSize:selected==i?11:9,letterSpacing:2.5,color:Colors.white.withValues(alpha:a))))));}
  int? _hit(Offset p,double d,double rot){final c=Offset(d/2,d/2),r=d*.47;const base=[Offset(-.22,-.25),Offset(.27,-.18),Offset(-.20,.27),Offset(.23,.23)];const scales=[.34,.29,.37,.30];for(var i=0;i<4;i++){final a=base[i].dx+math.sin(rot*math.pi*2+i)*.018, y=base[i].dy;final q=c+Offset(a*r,y*r);if((p-q).distance<r*scales[i])return i;}return null;}
}
class _PlanetPainter extends CustomPainter{
 final int? selected;final double rotation;const _PlanetPainter({required this.selected,required this.rotation});
 static const centers=[Offset(-.22,-.25),Offset(.27,-.18),Offset(-.20,.27),Offset(.23,.23)];
 static const sizes=[Offset(.70,.46),Offset(.50,.39),Offset(.65,.48),Offset(.51,.40)];
 static const colors=[Color(0xFF9175A9),Color(0xFF66829A),Color(0xFF786C98),Color(0xFF5D847A)];
 @override void paint(Canvas canvas,Size s){final c=Offset(s.width/2,s.height/2),r=s.shortestSide*.47,sphere=Rect.fromCircle(center:c,radius:r),rnd=math.Random(442);canvas.drawCircle(c,r*1.58,Paint()..shader=const RadialGradient(colors:[Color(0x596E83AA),Color(0x1B52688E),Colors.transparent],stops:[0,.46,1]).createShader(Rect.fromCircle(center:c,radius:r*1.58)));canvas.drawCircle(c,r*1.035,Paint()..shader=const RadialGradient(center:Alignment(-.55,-.60),radius:1.12,colors:[Color(0xFFE0D5C7),Color(0xFFA49D99),Color(0xFF676974),Color(0xFF272A35),Color(0xFF05070D)],stops:[0,.13,.35,.68,1]).createShader(sphere)));canvas.save();canvas.clipPath(Path()..addOval(sphere));
   for(var p=0;p<4;p++){final drift=math.sin(rotation*math.pi*2+p)*r*.018;final tc=c+Offset((centers[p].dx+drift/r)*r,centers[p].dy*r);final depth=(tc.dy-c.dy)/r,side=(tc.dx-c.dx)/r;final w=r*sizes[p].dx,h=r*sizes[p].dy;final curve=math.sqrt(math.max(.06,1-side*side));final lat=math.sqrt(math.max(.06,1-depth*depth));final center=tc+Offset(-side*r*.05,depth*r*.025);final pw=w*(.68+.32*curve),ph=h*(.74+.26*lat);final rot=[.18,-.24,-.08,.25][p];final alpha=selected==null?.34:selected==p?.82:.012;
     final shadow=_shape(center+Offset(r*.018,r*.035),pw*1.04,ph*1.06,rot,1900+p*31);canvas.drawPath(shadow,Paint()..color=Colors.black.withValues(alpha:selected==p?.34:.18));
     final path=_shape(center,pw,ph,rot,700+p*19);canvas.drawPath(path,Paint()..color=colors[p].withValues(alpha:alpha));canvas.drawPath(path,Paint()..style=PaintingStyle.stroke..strokeWidth=r*(selected==p?.016:.006)..color=Colors.white.withValues(alpha:selected==p?.42:.065));
     for(var q=1;q<=9;q++){final sc=1-q*.083;final inner=_shape(center+Offset(-side*r*.007*q,depth*r*.004*q),pw*sc,ph*sc,rot,740+p*19+q*23);canvas.drawPath(inner,Paint()..style=PaintingStyle.stroke..strokeWidth=r*.003..color=Colors.white.withValues(alpha:selected==p?.075:.012));}
     for(var band=0;band<7;band++){final t=(band-3)*.145,y=center.dy+t*ph,left=center.dx-pw*.46,right=center.dx+pw*.46;final path=Path()..moveTo(left,y);for(var k=1;k<=20;k++){final u=k/20;final x=left+(right-left)*u;final bend=math.sin(u*math.pi)*ph*(.10+.10*(1-t.abs()));final wave=math.sin(u*math.pi*2.2+band+p)*ph*.022;path.lineTo(x,y-bend+wave);}canvas.drawPath(path,Paint()..style=PaintingStyle.stroke..strokeWidth=r*.0038..color=Colors.white.withValues(alpha:selected==p?.065:.017));}
     final low=_shape(center+Offset(r*.006,r*.019),pw*.99,ph*.99,rot,1600+p*23);canvas.drawPath(low,Paint()..style=PaintingStyle.stroke..strokeWidth=r*.008..color=Colors.black.withValues(alpha:selected==p?.27:.07));
     for(var ridge=0;ridge<4;ridge++){final y=center.dy+(ridge-1.5)*ph*.19,path=Path()..moveTo(center.dx-pw*.32,y);for(var k=1;k<=10;k++){final u=k/10;path.lineTo(center.dx-pw*.32+pw*.64*u,y+math.sin(u*math.pi*2.4+ridge+p)*ph*.075);}canvas.drawPath(path,Paint()..style=PaintingStyle.stroke..strokeWidth=r*.004..color=Colors.black.withValues(alpha:selected==p?.11:.025));}
   }
   for(var i=0;i<8;i++){final t=-.78+i*.22,half=r*math.sqrt(math.max(0,1-t*t));canvas.drawOval(Rect.fromCenter(center:Offset(c.dx+t*r*.18,c.dy),width:half*1.5,height:r*.025),Paint()..style=PaintingStyle.stroke..strokeWidth=r*.0025..color=Colors.white.withValues(alpha:.010));}
   for(var i=0;i<120;i++){final a=rnd.nextDouble()*math.pi*2,rr=r*(.1+rnd.nextDouble()*.82);canvas.drawCircle(Offset(c.dx+math.cos(a)*rr,c.dy+math.sin(a)*rr*.78),r*(.0007+rnd.nextDouble()*.0035),Paint()..color=Colors.white.withValues(alpha:.005+rnd.nextDouble()*.018));}canvas.restore();
   final night=c+Offset(r*.59,r*.09);canvas.drawCircle(night,r*.96,Paint()..shader=const RadialGradient(colors:[Colors.transparent,Color(0xE0000208)],stops:[.24,1]).createShader(Rect.fromCircle(center:night,radius:r*.96)));canvas.drawArc(Rect.fromCircle(center:c,radius:r*1.01),math.pi*.58,math.pi*.94,false,Paint()..style=PaintingStyle.stroke..strokeWidth=r*.014..color=Colors.white.withValues(alpha:.31));canvas.drawArc(Rect.fromCircle(center:c,radius:r*1.02),math.pi*1.04,math.pi*.86,false,Paint()..style=PaintingStyle.stroke..strokeWidth=r*.02..color=const Color(0x668CA4C7));}
 Path _shape(Offset c,double w,double h,double rot,int seed){final rnd=math.Random(seed),pts=<Offset>[];const n=30;for(var i=0;i<n;i++){final a=i/n*math.pi*2,wave=math.sin(a*2.1+seed)*.14+math.sin(a*3.7+seed*.1)*.09+math.sin(a*6.5+seed*.07)*.045;final rad=.80+wave+rnd.nextDouble()*.075,x=math.cos(a)*w*.5*rad,y=math.sin(a)*h*.5*rad*(.88+.12*math.sin(a*2.6+seed)),xr=x*math.cos(rot)-y*math.sin(rot),yr=x*math.sin(rot)+y*math.cos(rot);pts.add(Offset(c.dx+xr,c.dy+yr));}final p=Path()..moveTo(pts[0].dx,pts[0].dy);for(var i=0;i<n;i++){final a=pts[i],b=pts[(i+1)%n],m=Offset((a.dx+b.dx)/2,(a.dy+b.dy)/2);p.quadraticBezierTo(a.dx,a.dy,m.dx,m.dy);}return p..close();}
 @override bool shouldRepaint(covariant _PlanetPainter old)=>old.selected!=selected||old.rotation!=rotation;
}
class _SpacePainter extends CustomPainter{final double t;const _SpacePainter({required this.t});@override void paint(Canvas c,Size s){final rect=Offset.zero& s;c.drawRect(rect,Paint()..shader=const RadialGradient(center:Alignment(0,-.08),radius:1.1,colors:[Color(0xFF15162A),Color(0xFF060710),Color(0xFF010205)]).createShader(rect));final r=math.Random(711);for(var i=0;i<220;i++){final x=(r.nextDouble()*s.width+t*s.width*.018)%s.width;c.drawCircle(Offset(x,r.nextDouble()*s.height),.15+r.nextDouble()*.7,Paint()..color=Colors.white.withValues(alpha:.025+r.nextDouble()*.09));}}@override bool shouldRepaint(covariant _SpacePainter old)=>old.t!=t;}
